name: fbh_front_matter
version: 0.0.1
description: A front matter parser that extracts YAML metadata from the start of a file or string.
homepage: https://github.com/flutter-bounty-hunters/fbh_front_matter

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  yaml: ^3.1.1
dev_dependencies:
  test: ^1.21.6
